// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIUL5YFTS9RrKAEKqF4rF2cypoyrKN-J0',
    appId: '1:325848045623:web:948ca530a0e375d23d47b2',
    messagingSenderId: '325848045623',
    projectId: 'fir-flutter-codelab-ff247',
    authDomain: 'fir-flutter-codelab-ff247.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-ff247.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV08l5z0eKo4Stu02Pkig-R0blYRQTOsg',
    appId: '1:325848045623:android:8a0d39c237afea683d47b2',
    messagingSenderId: '325848045623',
    projectId: 'fir-flutter-codelab-ff247',
    storageBucket: 'fir-flutter-codelab-ff247.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDK1FLXfcJH4Q8AoR_S4EDo6-AJINix5o',
    appId: '1:325848045623:ios:f8780a80bd042e413d47b2',
    messagingSenderId: '325848045623',
    projectId: 'fir-flutter-codelab-ff247',
    storageBucket: 'fir-flutter-codelab-ff247.appspot.com',
    iosClientId: '325848045623-504fer4gkadb7rvd20ak8e4gvclosqse.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDK1FLXfcJH4Q8AoR_S4EDo6-AJINix5o',
    appId: '1:325848045623:ios:f8780a80bd042e413d47b2',
    messagingSenderId: '325848045623',
    projectId: 'fir-flutter-codelab-ff247',
    storageBucket: 'fir-flutter-codelab-ff247.appspot.com',
    iosClientId: '325848045623-504fer4gkadb7rvd20ak8e4gvclosqse.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
